### ISSUE TITLE
This fix is not needed now for default value changed to "-1.0f"

### ISSUE THREAD

**Issue by ameaninglessname** [Vaei/AbilitySystemFix#1]
```C++
	virtual void CurrentMontageStop(float OverrideBlendOutTime = -1.0f);
```

**Comment by Vaei** [comment]
It is needed. Here is the callstack. `OnRep_ReplicatedAnimMontage` calls `CurrentMontageStop(ConstRepAnimMontageInfo.BlendTime)` which has a value of `0.f`, the fix makes it check that it is `> 0.f`, so the default value is irrelevant.

```
UAbilitySystemComponentFix::CurrentMontageStop(float) AbilitySystemComponentFix.cpp:16
UAbilitySystemComponent::OnRep_ReplicatedAnimMontage() AbilitySystemComponent_Abilities.cpp:2969
UFunction::Invoke(UObject *,FFrame &,void *const) Class.cpp:6411
```

**Comment by Vaei** [comment]
I have submitted a pull request now that Epic might be taking them again. https://github.com/EpicGames/UnrealEngine/pull/10574
